### ISSUE TITLE
How to segregate allure results pushed to repository

### ISSUE THREAD

**Issue by mathewkuruvila** [simple-elf/allure-report-action#30]
First of thanks for developing this beautiful utility. This really helps me a lot.

Currently I have automation tests for IOS/Android devices and both have same set of test cases for both the platform. I have got different workflows - smoke, regression etc. etc. So there will be IOS Smoke and Android Smoke likewise regression too. But the allure-results from all of these executions are pushed to same folder in repository. So the history of android testcase will be showing the executions in ios too. 

<img width="784" alt="image" src="https://user-images.githubusercontent.com/866753/172279094-e50b4954-0062-4450-bf59-c6e11615e675.png">

Similarly the graphs, trends are all messed up as it will having smoke/regression runs. Not sure how to keep these execution results in separate folder so allure will be showing only test cases for specific platform.

**Comment by mrehkemper-moodys** [comment]
I would also like this. 

@mathewkuruvila Were you able to get more than one suite loaded into your reports? 
I have multiple workflows and the latest one overwrites all my results for the prior one. So when I go to the suites tab, it only has the latest one. I havent been able to figure out how to have multiple suites from different runs.

**Comment by mathewkuruvila** [comment]
I think that's how allure report works. It just shows the latest execution report in "suite" tab.

**Comment by mathewkuruvila** [comment]
Thanks for the help. I tried the same. I can push it into different folders. But now the problem is like I am missing historical data. Now allure just shows the current execution status and history is empty.

**Comment by mathewkuruvila** [comment]
Got this working by adding "subfolder". Now reports are segregated. Details about "subfolder" are mentioned in the documentation. Thanks again for this great product.

**Comment by priyanka-kahare-kr** [comment]
@mathewkuruvila  Can you post the final code snippet on how you used the subfolder as resolution for this question?

**Comment by mathewkuruvila** [comment]
Just use below code. It has "subfolder" in it.

    - name: Generate allure Reports
      uses: simple-elf/allure-report-action@v1
      if: always()
      continue-on-error: true
      id: allure-report
      with:
          allure_results: allure-results
          gh_pages: gh-pages
          subfolder: Android
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 15
