### ISSUE TITLE
How to generate allure report for more than one workflow in the same repo

### ISSUE THREAD

**Issue by prakashchakrapani** [simple-elf/allure-report-action#34]
In my repo , i have multiple workflows for iOS , Android and other OS . When i try to publish the allure-report to gh-pages , the reports are getting overwritten . How to overcome this issue?

**Comment by Foxtel-chenfan** [comment]
try with subfolder parameter like this, this will separate your report into each subfolder
` - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          subfolder: IOS
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 8`

**Comment by prakashchakrapani** [comment]
At first it did not work if i did not clean up the existing report. After cleaning up , it worked . Thanks much!!! Now i can add multiple reports without any hassle!!
