### ISSUE TITLE
[Workflow config Issue?] report doesn't contain data when run from github action 

### ISSUE THREAD

**Issue by jpatel01-tc** [simple-elf/allure-report-action#38]
Hi, 
 
This might be a misunderstanding on my part, but the issue is when I go to the github page no test data is displayed. 
I pulled the gh-pages branch to my local and was able to success fully serve the report with test results.  e.g. allure serve reports/qa/testjobs 

My setup is as follows
1. I have a project which has a subtree reports -> points to the gh-pages branch 
2. My Allure Results (json) are pushed to the gh-pages branch under qa/<product> folder after tests are run via github action 
3. My git hub work flow below for how I am integrating the allure-report-action 
`generate_allure_report:
     needs: run-tests 
     name: generate test report
     runs-on: <self hosted> 
     steps:   
      - uses: actions/checkout@v2  
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages       
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        # id: allure-report
        with:
         allure_results: qa/<product> 
        # gh_pages: gh-pages
        # allure_report: allure-report
         allure_history: allure-history
         keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ALLUREPAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
`
Any help on understanding what I'm doing wrong would be greatly appreciated. Thanks!

**Comment by mgrybyk** [comment]
Hello,

@jpatel01-tc @praful-transcarent I may suggest using https://github.com/marketplace/actions/allure-report-with-history-per-branch

Please follow the instructions and enable Github Pages in your repository settings.

**Comment by jpatel01-tc** [comment]
> hi @jpatel01-tc did you find a resolution to this ?

yes I was able to make it work.

**Comment by mgrybyk** [comment]
@jpatel01-tc can you close the ticket in such a case?
