### ISSUE TITLE
Request to Update to Allure 2.19.0 or Later

### ISSUE THREAD

**Issue by patrick-kilburn** [simple-elf/allure-report-action#46]
The current version of Allure used in the action is 2.18.1: https://github.com/simple-elf/allure-report-action/blob/master/Dockerfile#L3C13-L3C19

I'm hoping to use the search by tag feature which allows filtering of test cases within the HTML report based on their tag. This feature was added in 2.19.0:
https://github.com/allure-framework/allure2/releases/tag/2.19.0

The latest version appears to be 2.23.1:
https://github.com/allure-framework/allure2/releases

Assuming that new Allure versions are backwards compatible, updating the version should carry minimal risk. We have a workaround that requires generating the report locally with the newer version of Allure, but this is not ideal as our source of truth is generated by this Action.
Thank you!

**Comment by mgrybyk** [comment]
@patrick-kilburn Hello,
I'm not sure if this action is still maintained. I may suggest using https://github.com/marketplace/actions/allure-report-with-history-per-branch that uses allure version 2.23.1

**Comment by patrick-kilburn** [comment]
Thanks @mgrybyk, I'll take a look.

**Comment by alcpereira** [comment]
#47 solves it.

**Comment by patrick-kilburn** [comment]
Thank you!
