### ISSUE TITLE
environment.properties are overwritten after allure report generation  

### ISSUE THREAD

**Issue by bogdan-lykhyi** [simple-elf/allure-report-action#9]
I add the some environment properties to the environment.properties file, and I expect them in the report, but for some reason you do this 

#environment.properties
echo "URL=${GITHUB_PAGES_WEBSITE_URL}" > environment.properties
mv ./environment.properties ./${INPUT_ALLURE_RESULTS}

which overwrites my data.

**Comment by aleksandar-stefanovic-tamedia** [comment]
I have the same problem. I'm generating environment.properties file from @After hook but generated report contains only a URL which is GitHubPage URL.

**Comment by goncer** [comment]
Created this PR to solve the issue. 
Does anybody know if this project is no longer maintained? 
https://github.com/simple-elf/allure-report-action/pull/15
